# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FrontierPsychiatrist
email: moritz@frontierpsychiatrist.de
description: > # this means to ignore newlines until "baseurl:"
  Homepage about the music and programmin projects of Moritz Schulze.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://frontierpsychiatrist.de" # the base hostname & protocol for your site
github_username:  FrontierPsychiatrist

# Build settings
markdown: kramdown
permalink: /blog/:title
include: [".well-known"]
