baseURL = "https://frontierpsychiatrist.de"
languageCode = "en-us"
title = "FrontierPsychiatrist"
theme = "cactus"
publishDir = "docs"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Music"
  url = "/music"
  weight = 3

[[params.social]]
  name = "github"
  link = "https://github.com/FrontierPsychiatrist"

[[params.social]]
  name = "email"
  link = "moritz@frontierpsychiatrist.de"

[[params.social]]
  name = "soundcloud"
  link = "https://soundcloud.com/moritz-schulze"
